<?php

namespace Database\Seeders;

use App\Models\Producto;
use Illuminate\Database\Seeder;
use Faker;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $productos=[
            "Aceite comestibles",
            "Aderezos",
            "Consome",
            "Crema de cacahuate",
            "Crema para café",
            "Pure de tomate",
            "Alimento para bebe",
            "Alimento para mascotas",
            "Atole",
            "Avena",
            "Azúcar",
            "Café",
            "Cereales",
            "Chile piquín",
            "Especias",
            "Flan en polvo",
            "Formulas infantiles",
            "Gelatinas en polvo/Grenetina",
            "Harina",
            "Harina preparada",
            "Mole",
            "Sal",
            "Salsas envasadas",
            "Sazonadores",
            "Sopas en sobre",
            "Cajeta",
            "Catsup",
            "Mayonesa",
            "Mermelada",
            "Miel",
            "Te",
            "Vinagre",
            "Huevo",
            "Pastas",
            "Aceitunas",
            "Champiñones enteros/rebanados",
            "Chícharo con zanahoria",
            "Chícharos enlatados",
            "Frijoles enlatados",
            "Frutas en almíbar",
            "Sardinas",
            "Atún en agua/aceite",
            "Chiles enlatados",
            "Chiles envasados",
            "Ensaladas enlatadas",
            "Granos de elote enlatados",
            "Sopa en lata",
            "Vegetales en conserva",
            "Leche condesada",
            "Leche deslactosada",
            "Leche en polvo",
            "Leche evaporada",
            "Leche light",
            "Leche pasteurizada",
            "Leche saborizada",
            "Leche semidescremada",
            "Crema",
            "Yoghurt",
            "Mantequilla",
            "Margarina",
            "Media crema",
            "Queso",
            "Papa",
            "Palomitas",
            "Frituras de maíz",
            "Cacahuates",
            "Botanas saladas",
            "Barras alimenticias",
            "Nueces y semillas",
            "Caramelos",
            "Dulces enchilados",
            "Chocolate de mesa",
            "Chocolate en polvo",
            "Chocolates",
            "Gomas de mascar",
            "Mazapán",
            "Malvaviscos",
            "Pulpa de tamarindo",
            "Pastillas de dulce",
            "Paletas de dulce",
            "Tortillas de harina/maíz",
            "Galletas dulces",
            "Galletas saladas",
            "Pastelillos",
            "Pan de caja",
            "Pan dulce",
            "Pan molido",
            "Pan tostado",
            "Aguacates",
            "Ajos",
            "Cebollas",
            "Chiles",
            "Cilantro/Perejil",
            "Jitomate",
            "Papas",
            "Limones",
            "Manzanas",
            "Naranjas",
            "Plátanos",
            "Agua mineral",
            "Agua natural",
            "Agua saborizada",
            "Jarabes",
            "Jugos/Néctares",
            "Naranjadas",
            "Bebidas de soya",
            "Bebidas en polvo",
            "Bebidas infantiles",
            "Bebidas isotónicas",
            "Energetizantes",
            "Isotónicos",
            "Refrescos",
            "Bebidas preparadas",
            "Cerveza",
            "Anís",
            "Brandy",
            "Ginebra",
            "Cordiales",
            "Mezcal",
            "Jerez",
            "Ron",
            "Tequila",
            "Sidra",
            "Whiskey",
            "Vodka",
            "Pastas listas para comer",
            "Sopas en vaso",
            "Carnes y Embudos",
            "Salchicha",
            "Mortadela",
            "Tocino",
            "Jamón",
            "Manteca",
            "Chorizo",
            "Carne de puerco/res/pollo",
            "Suero",
            "Agua oxigenada",
            "Preservativos",
            "Alcohol",
            "Gasas",
            "Analgésicos",
            "Antigripales",
            "Antiácidos",
            "Toallas húmedas",
            "Aceite para bebe",
            "Toallas femeninas",
            "Algodón",
            "Tinte para el cabello",
            "Biberones",
            "Talco",
            "Cepillo de dientes",
            "Shampoo/ Acondicionador",
            "Cotonetes",
            "Rastrillos",
            "Crema corporal/facial",
            "Papel higiénico",
            "Crema para afeitar",
            "Pañuelos faciales",
            "Dentífricos",
            "Pañuelos desechables",
            "Desodorantes en barra/aerosol",
            "Maquillaje",
            "Enjuague bucal",
            "Lubricantes para labios",
            "Gel/spray",
            "Loción hidratante",
            "Jabones corporales/tocados",
            "Suavizante de telas",
            "Ácido muriático",
            "Sosa caustica",
            "Aluminio",
            "Pilas",
            "Shampoo para ropa",
            "Servilletas",
            "Servitoallas",
            "Aromatizantes",
            "Cera para automóvil",
            "Cera para calzados",
            "Pastillas sanitarias",
            "Limpiadores líquidos",
            "Limpiadores para pisos",
            "Jabón de barra",
            "Cerillos",
            "Cloro/Blanqueador",
            "Cloro para ropa",
            "Jabón en barra",
            "Insecticidas",
            "Fibras limpiadoras",
            "Desinfectantes",
            "Detergentes para trastes",
            "Detergente para ropa",
            "Paletas/ Helados",
            "Veladoras/Velas",
            "Cepillo de plástico",
            "Vasos desechables",
            "Cinta adhesiva",
            "Cucharas de plástico",
            "Escobas/Trapeadores/Mechudos",
            "Trampas para ratas",
            "Tenedores de plásticoa",
            "Extensiones/Multicontacto",
            "Recogedor de metal/plástico",
            "Popotes",
            "Platos desechables",
            "Focos",
            "Fusibles",
            "Jergas/Franelas",
            "Matamoscas",
            "Pegamento",
            "Mecate/cuerda",
            "Tarjetas telefónicas",
            "Recargas móviles",
            "Hielo",
            "Cigarros"
        ];
        $faker = Faker\Factory::create();

        foreach ($productos as $producto){
            $productoModel                       =   new Producto();
            $productoModel->nombre               =   $producto;
            $productoModel->descripcion          =   $producto;
            $productoModel->imagen               =   $faker->imageUrl(640,480,$producto);
            $productoModel->id_producto_estado   =   1;
            $productoModel->save();
        }
    }
}
